version: "3.8"
services:
  try-gpt-4:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: try-gpt-4
    working_dir: /go/src/
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/
    ports:
      - "9090:9090"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
